### ISSUE TITLE
优化GRPC，成为高可用状态

### ISSUE THREAD

**Issue by jcai** [wechaty/scala-wechaty#3]
优化GRPC，成为高可用状态

**Comment by jcai** [comment]
通过定时发送ding消息，目前测试来看没有太大问题，不过从程序设计角度看，不是很好，主要是目前对后端的GRPC Server了解甚少，譬如有无ping消息支持之类。

**Comment by diaozxin007** [comment]
可以考虑写一个 netty 的 IDLE handler.
